# Generated by Django 4.1.3 on 2022-11-11 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oasis', '0002_remove_stock_product_quantity_remained_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='complited',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='key',
            field=models.CharField(blank=True, default='WGAGHPUI5UDA5XUZLYKYMKYGVJG2JT3R', max_length=200, null=True),
        ),
    ]
