# Generated by Django 4.1.3 on 2022-11-11 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oasis', '0003_sales_complited_alter_user_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='is_wholesale',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='key',
            field=models.CharField(blank=True, default='U7BUUEVMEXCLGEKQRTTDPKL5ZISWSC4P', max_length=200, null=True),
        ),
    ]
