# Generated by Django 4.1.3 on 2022-11-15 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oasis', '0004_sales_is_wholesale_alter_user_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='entry_date',
            field=models.DateField(auto_now=True, verbose_name='Entry Date'),
        ),
        migrations.AlterField(
            model_name='user',
            name='key',
            field=models.CharField(blank=True, default='ZZ37KOREBGZC6KGYVEOK2H7YJ6JR77EI', max_length=200, null=True),
        ),
    ]
