# Generated by Django 4.1.3 on 2022-11-18 10:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oasis', '0005_alter_stock_entry_date_alter_user_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='sold_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stock',
            name='added_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='costomer',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Costomer Name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='key',
            field=models.CharField(blank=True, default='OCNXU73IBPVD3VRY7SFYTO7XSCTYDLUD', max_length=200, null=True),
        ),
    ]
